<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media')->delete();
        
        \DB::table('media')->insert(array (
            0 => 
            array (
                'id' => 1,
                'model_type' => 'App\\Models\\Portofilo',
                'model_id' => 1,
                'uuid' => 'a8254ad7-47d9-415b-9353-c4aac904e9b9',
                'collection_name' => 'portofilo',
                'name' => '',
                'file_name' => 'FeCL8b5Qg0CkkS5ebKz7jQ1dkaEgI1-metaMTQ0NzYxOTkxLWQ1YmIwZDMwLWQ3NDgtNGI3OS1iYmRlLWVmMzM2MmRhODIzMS5wbmc=-.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 29892,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2022-05-21 00:13:32',
                'updated_at' => '2022-05-21 00:13:33',
            ),
            1 => 
            array (
                'id' => 5,
                'model_type' => 'App\\Models\\Portofilo',
                'model_id' => 2,
                'uuid' => '2d034424-c184-4ace-b89a-efe06d31e352',
                'collection_name' => 'portofilo',
                'name' => '',
                'file_name' => 'EwvGgDx1MFd3OIi76l1CpRpLY4cB4L-metac2NyZWVuc2hvdC1hbHBldGdibG9nLmVwaXp5LmNvbS0yMDIyLjA1LjIxLTAyXzI2XzU4LnBuZw==-.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 451717,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2022-05-21 00:30:26',
                'updated_at' => '2022-05-21 00:30:27',
            ),
            2 => 
            array (
                'id' => 6,
                'model_type' => 'App\\Models\\Portofilo',
                'model_id' => 2,
                'uuid' => 'f039ab90-a9aa-45f5-9f75-628415b008a8',
                'collection_name' => 'portofilo',
                'name' => '',
                'file_name' => 'y5q9lfw94kmuhJbq3Pj5p9DLmOeIMq-metac2NyZWVuc2hvdC1hbHBldGdibG9nLmVwaXp5LmNvbS0yMDIyLjA1LjIxLTAyXzI2XzAyLnBuZw==-.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 280845,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 3,
                'created_at' => '2022-05-21 00:30:27',
                'updated_at' => '2022-05-21 00:30:28',
            ),
            3 => 
            array (
                'id' => 7,
                'model_type' => 'App\\Models\\Portofilo',
                'model_id' => 2,
                'uuid' => 'f831b0d7-b61c-4665-afc3-bb30225c8245',
                'collection_name' => 'portofilo',
                'name' => '',
                'file_name' => 'p1L0pRFeV8ewoLznGG1EtjeR42zS10-metac2NyZWVuc2hvdC1hbHBldGdibG9nLmVwaXp5LmNvbS0yMDIyLjA1LjIxLTAyXzI4XzUzLnBuZw==-.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 157615,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 4,
                'created_at' => '2022-05-21 00:30:28',
                'updated_at' => '2022-05-21 00:30:29',
            ),
            4 => 
            array (
                'id' => 10,
                'model_type' => 'App\\Models\\Portofilo',
                'model_id' => 5,
                'uuid' => 'f55c3f1a-d2ab-4b6c-b2b3-269c598ea373',
                'collection_name' => 'portofilo',
                'name' => '',
                'file_name' => 'SeqVDIHDTe2y6mgGOEgJ1nSiUkW7ZA-metaUmVzaXN0ZW5jYTEuanBn-.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 47882,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 7,
                'created_at' => '2022-05-21 00:43:48',
                'updated_at' => '2022-05-21 00:43:49',
            ),
            5 => 
            array (
                'id' => 11,
                'model_type' => 'App\\Models\\Portofilo',
                'model_id' => 5,
                'uuid' => '50f10710-7622-4a54-8bb9-5ce8a3af7fe5',
                'collection_name' => 'portofilo',
                'name' => '',
                'file_name' => 'aWQUR4jiEFDtXceafgt0eRNN6dT5yX-metadW5hemEyLmpwZw==-.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 59071,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 8,
                'created_at' => '2022-05-21 00:43:50',
                'updated_at' => '2022-05-21 00:43:51',
            ),
            6 => 
            array (
                'id' => 12,
                'model_type' => 'App\\Models\\Portofilo',
                'model_id' => 3,
                'uuid' => 'bd7768c5-1477-4909-9157-0a5f03003511',
                'collection_name' => 'portofilo',
                'name' => '',
                'file_name' => 'ojNqVwcURgzxvGVJOFZjywgCEDLPEe-metabm5peGhhMS5qcGc=-.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 173867,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 9,
                'created_at' => '2022-05-21 00:59:34',
                'updated_at' => '2022-05-21 00:59:35',
            ),
            7 => 
            array (
                'id' => 13,
                'model_type' => 'App\\Models\\Portofilo',
                'model_id' => 3,
                'uuid' => 'd73a3797-00d7-4295-9655-edc1fca2cb16',
                'collection_name' => 'portofilo',
                'name' => '',
                'file_name' => 'dQDsOAdHyn93G7nSqnYzDkwHuZx3fz-metac2NyZWVuc2hvdC0xMjcuMC4wLjFfODAwMC0yMDIyLjA1LjIxLTAyXzU3XzQxLnBuZw==-.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 150355,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 10,
                'created_at' => '2022-05-21 00:59:35',
                'updated_at' => '2022-05-21 00:59:36',
            ),
            8 => 
            array (
                'id' => 14,
                'model_type' => 'App\\Models\\Portofilo',
                'model_id' => 3,
                'uuid' => '3d5848ef-8075-444e-addc-e6bbef32b610',
                'collection_name' => 'portofilo',
                'name' => '',
                'file_name' => 'uyuc56KuTO4vVAMO4DSVbP0YEFG8A9-metac2NyZWVuc2hvdC0xMjcuMC4wLjFfODAwMC0yMDIyLjA1LjIxLTAyXzU1XzQ0LnBuZw==-.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 192592,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 11,
                'created_at' => '2022-05-21 00:59:37',
                'updated_at' => '2022-05-21 00:59:38',
            ),
            9 => 
            array (
                'id' => 15,
                'model_type' => 'App\\Models\\Portofilo',
                'model_id' => 3,
                'uuid' => '042f292c-0afd-4006-8fd9-92f956552a61',
                'collection_name' => 'portofilo',
                'name' => '',
                'file_name' => '5NXwnc0G169flAYogDwcwjy61Cj3Gs-metac2NyZWVuc2hvdC0xMjcuMC4wLjFfODAwMC0yMDIyLjA1LjIxLTAyXzUzXzAxLnBuZw==-.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 44822,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 12,
                'created_at' => '2022-05-21 00:59:38',
                'updated_at' => '2022-05-21 00:59:39',
            ),
            10 => 
            array (
                'id' => 16,
                'model_type' => 'App\\Models\\Portofilo',
                'model_id' => 4,
                'uuid' => '4720a605-616c-4f32-b851-7c62a5425af0',
                'collection_name' => 'portofilo',
                'name' => '',
                'file_name' => 'b61couXJ6MWaHCvFHlCTsxgXstxzef-metaZmlyc3QxLmpwZw==-.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 83894,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 13,
                'created_at' => '2022-05-21 01:27:35',
                'updated_at' => '2022-05-21 01:27:36',
            ),
            11 => 
            array (
                'id' => 17,
                'model_type' => 'App\\Models\\Portofilo',
                'model_id' => 4,
                'uuid' => '60a02a13-da2d-49a1-bd99-11cc32a30836',
                'collection_name' => 'portofilo',
                'name' => '',
                'file_name' => 'nOQmw3KRfGne6ypelx0omIPLm0gitC-metaZmlyc3QyLmpwZw==-.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 119469,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 14,
                'created_at' => '2022-05-21 01:27:36',
                'updated_at' => '2022-05-21 01:27:37',
            ),
            12 => 
            array (
                'id' => 18,
                'model_type' => 'App\\Models\\Portofilo',
                'model_id' => 4,
                'uuid' => '3cb8bc71-2776-4123-bf3d-23270a969eaf',
                'collection_name' => 'portofilo',
                'name' => '',
                'file_name' => 'EmdIPYRpC4RLluEwvn6JOfr5Z3Jlxx-metaZmlyc3QzLmpwZw==-.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 77515,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 15,
                'created_at' => '2022-05-21 01:27:37',
                'updated_at' => '2022-05-21 01:27:38',
            ),
            13 => 
            array (
                'id' => 19,
                'model_type' => 'App\\Models\\Portofilo',
                'model_id' => 4,
                'uuid' => '29d715dc-bcab-4f42-9fdc-32bbd5fdd2a3',
                'collection_name' => 'portofilo',
                'name' => '',
                'file_name' => 'ehPT1s1OtCMdyhvAOtu2dlr4wRhewo-metaZmlyc3Q0LmpwZw==-.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 82219,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 16,
                'created_at' => '2022-05-21 01:27:38',
                'updated_at' => '2022-05-21 01:27:39',
            ),
            14 => 
            array (
                'id' => 20,
                'model_type' => 'App\\Models\\Portofilo',
                'model_id' => 4,
                'uuid' => 'a1381722-1227-431b-8dc2-bd31f076b608',
                'collection_name' => 'portofilo',
                'name' => '',
                'file_name' => 'NJsqIeDoqOkLLNWw0hcPEiYYpg8iMj-metaZmlyc3Q1LmpwZw==-.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 97356,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 17,
                'created_at' => '2022-05-21 01:27:39',
                'updated_at' => '2022-05-21 01:27:40',
            ),
            15 => 
            array (
                'id' => 21,
                'model_type' => 'App\\Models\\Portofilo',
                'model_id' => 4,
                'uuid' => 'ee8d4844-0da5-471a-8a28-92a6a05dac0c',
                'collection_name' => 'portofilo',
                'name' => '',
                'file_name' => 'xBKdyV3KQZG46qamzOYzNsGZzOv92O-metaZmlyc3Q2LmpwZw==-.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 89200,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 18,
                'created_at' => '2022-05-21 01:27:41',
                'updated_at' => '2022-05-21 01:27:41',
            ),
            16 => 
            array (
                'id' => 22,
                'model_type' => 'App\\Models\\Posts',
                'model_id' => 1,
                'uuid' => '6fd77798-694c-4c4a-87c5-689d2d71d524',
                'collection_name' => 'posts',
                'name' => '',
                'file_name' => 'T8sjGNtDQtyKm8rosPnbegD8QYEkfC-metaTGFyYXZlbC05LmpwZw==-.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 70210,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 19,
                'created_at' => '2022-05-21 01:32:35',
                'updated_at' => '2022-05-21 01:32:36',
            ),
            17 => 
            array (
                'id' => 23,
                'model_type' => 'App\\Models\\Posts',
                'model_id' => 2,
                'uuid' => '94487875-62b3-4d3d-9fe7-c8ac8cbd1be3',
                'collection_name' => 'posts',
                'name' => '',
                'file_name' => 'Dv29j6rJHFLfHxbJvtHjjbtSfgC8vu-metabWF4cmVzZGVmYXVsdC5qcGc=-.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 98342,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 20,
                'created_at' => '2022-05-21 01:40:18',
                'updated_at' => '2022-05-21 01:40:19',
            ),
            18 => 
            array (
                'id' => 24,
                'model_type' => 'App\\Models\\Posts',
                'model_id' => 3,
                'uuid' => 'a4eb86dc-c9ba-49e5-8244-8969df752274',
                'collection_name' => 'posts',
                'name' => '',
                'file_name' => 'jCQaL2qP9egEOHOzZjOk0H12qCJvkh-metabGFyYXZlbC1mZWF0dXJlZC5wbmc=-.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 138769,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb":true,"test":true}',
                'responsive_images' => '[]',
                'order_column' => 21,
                'created_at' => '2022-05-21 01:49:55',
                'updated_at' => '2022-05-21 01:49:56',
            ),
        ));
        
        
    }
}